### ISSUE TITLE
Add the login data to webdesigniorc.json (find a better way)

### ISSUE THREAD

**Issue by pA1nD** [webdesignio/webdesignio#4]
The way we add the login data is a bit hacky at the moment. Can we change it?

Docu says:
`cat ~/.netrc` and add the login data to `./.webdesigniorc.json`
    it should look like:

```
{
  "url": "https://webdesignio.de",
  "id": "pa1nd",
  "token": "...",
  "config": {
    "domain": "<<SOME FREE SUBDOMAIN>>.surge.sh",
    "surge": {
      "email": "...",
      "token": "..."
    },
    "driver": "surge"
  }
}
```

**Comment by domachine** [comment]
I think this can be closed. Since we already enhanced the `init` command for the cli.
